# Generated by Django 3.2.1 on 2021-05-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='about',
        ),
        migrations.RemoveField(
            model_name='task',
            name='age',
        ),
        migrations.RemoveField(
            model_name='task',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='task',
            name='company',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contactDetails',
        ),
        migrations.RemoveField(
            model_name='task',
            name='eyeColor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='favoriteFruit',
        ),
        migrations.RemoveField(
            model_name='task',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='task',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='task',
            name='greetings',
        ),
        migrations.RemoveField(
            model_name='task',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='task',
            name='index',
        ),
        migrations.RemoveField(
            model_name='task',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='task',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='task',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='task',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.JSONField(default='{}'),
        ),
    ]
